PUT http://localhost:8080/api/v1/private/resource/node/taint
Content-Type: application/json

{
  "name": "worker6-ubuntu-seoul",
  "key": "kkk",
  "value": "vvv",
  "effect": "NoSchedule"
}

###
PUT http://localhost:8080/api/v1/private/resource/node/taint
Content-Type: application/json

{
  "name": "worker6-ubuntu-seoul",
  "key": "123",
  "effect": "NoSchedule"
}

### fail
PUT http://localhost:8080/api/v1/private/resource/node/taint
Content-Type: application/json

{
  "name": "worker6-ubuntu-seoul",
  "effect": "NoSchedule"
}

###
DELETE http://localhost:8080/api/v1/private/resource/node/taint
Content-Type: application/json

{
  "name": "worker3-ubuntu-seoul",
  "key": "kkk"
}

### fail
PUT http://localhost:8080/api/v1/private/resource/node/taint
Content-Type: application/json

{
  "name": "worker6-ubuntu-seoul",
  "effect": "NoSchedule"
}

###
PUT http://localhost:8080/api/v1/private/workload/deployment/toleration
Content-Type: application/json

{
  "name": "devzat-deployment",
  "key": "kkk",
  "effect": "NoSchedule",
  "operator": "Exists"
}

###
PUT http://localhost:8080/api/v1/private/workload/deployment/toleration
Content-Type: application/json

{
  "name": "devzat-deployment",
  "key": "node-role.kubernetes.io/control-plane",
  "effect": "NoSchedule"
}

###
PUT http://localhost:8080/api/v1/private/workload/deployment/toleration
Content-Type: application/json

{
  "name": "devzat-deployment",
  "key": "node-role.kubernetes.io/master",
  "effect": "NoSchedule"
}

###
DELETE http://localhost:8080/api/v1/private/workload/deployment/toleration
Content-Type: application/json

{
  "name": "devzat-deployment",
  "key": "node-role.kubernetes.io/control-plane"
}

###
PUT http://localhost:8080/api/v1/private/resource/node/taint/any
Content-Type: application/json

{
  "key": "kkk",
  "value": "vvv",
  "effect": "NoSchedule",
  "count": 3
}

###
DELETE http://localhost:8080/api/v1/private/resource/node/taint/any
Content-Type: application/json

{
  "key": "kkk",
  "count": 3
}
